### ISSUE TITLE
autoprefixer

### ISSUE THREAD

**Issue by frostbolt** [sergeynechaev/weblayout-template#3]
You could probably use `gulp-autoprefixer` instead of creating tons of mixins such as mentioned below.

``` scss
@mixin border-radius($radius) {
    -webkit-border-radius: $radius;
    -moz-border-radius: $radius;
    -ms-border-radius: $radius;
    border-radius: $radius;
}
```
